---
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Build template.
  name: "${NAME}-build-template"
objects:

  # - kind: NetworkSecurityPolicy
  #   apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
  #   metadata:
  #     name: pods-to-external-network
  #     labels:
  #       name: pods-to-external-network
  #       env: ${ENV_NAME}
  #   spec:
  #     description: |
  #       Allow the builds to access the internet.
  #       This only needs to be specified once per environment.
  #     source:
  #       - - $namespace=apndkr-${ENV_NAME}
  #     destination:
  #       - - ext:network=any

  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${NAME}"
      labels:
        name: "${NAME}"
        app: "${APP_NAME}${SUFFIX}"
        app-group: "${APP_GROUP}"
        env: ${ENV_NAME}

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${NAME}"
      labels:
        name: "${NAME}"
        app: "${APP_NAME}${SUFFIX}"
        app-group: "${APP_GROUP}"
        env: ${ENV_NAME}
    spec:
      source:
        type: Git
        git:
          uri: "${GIT_REPO_URL}"
          ref: "${GIT_REF}"
        contextDir: "${SOURCE_CONTEXT_DIR}"
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: "${SOURCE_IMAGE_TYPE}"
            namespace: "${SOURCE_IMAGE_NAMESPACE}"
            name: "${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}"
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}:${OUTPUT_IMAGE_TAG}"
      triggers:
        - type: ImageChange
        - type: ConfigChange

parameters:
  - name: NAME
    displayName: Name
    description:
      The name assigned to all of the objects defined in this template.  You
      should keep this as default unless your know what your doing.
    required: true
    value: website
  - name: SUFFIX
    displayName: Suffix
    description: A name suffix used for all objects
    required: false
    value: ""
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: Cullen-Commission-Website
  - name: APP_GROUP
    displayName: App Group
    description: The name assigned to all of the deployments in this project.
    required: true
    value: cullen-commission

  - name: ENV_NAME
    displayName: Environment Name
    description: Environment name.  For the build environment this will typically be 'tools'
    required: true
    value: tools

  - name: GIT_REPO_URL
    displayName: Git Repo URL
    description:
      The URL to your GIT repo, don't use the this default unless your just
      experimenting.
    required: true
    value: https://github.com/bcgov/jag-cullencommission.git
  - name: GIT_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: false
    value: 
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: false
    value: ""

  - name: SOURCE_IMAGE_TYPE
    displayName: Source Image Type
    required: true
    description: The type of the source image.
    value: ImageStreamTag
  
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    required: true
    description: The name of the source image.
    value: php
  - name: SOURCE_IMAGE_TAG
    displayName: Source Image Tag
    required: true
    description: The tag of the source image.
    value: "7.1"
  - name: SOURCE_IMAGE_NAMESPACE
    displayName: Namespace
    required: true
    description: The Namespace where the ImageStream resides.
    value: openshift

  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
    value: latest
